using Dapper;using Microsoft.Data.Sqlite;using LEGAL.Scadenze.Api.Models;
namespace LEGAL.Scadenze.Api.Repositories;
public class ScadenzeRepository{private readonly string _cs;public ScadenzeRepository(string cs)=>_cs=cs;private SqliteConnection C()=>new(_cs);
public async Task InitializeAsync(){using var c=C();await c.OpenAsync();await c.ExecuteAsync("CREATE TABLE IF NOT EXISTS scadenze(Id TEXT PRIMARY KEY,Tipo INTEGER NOT NULL,Titolo TEXT NOT NULL,Descrizione TEXT,DataScadenza TEXT NOT NULL,GiorniPreavviso INTEGER DEFAULT 7,Priorita INTEGER NOT NULL DEFAULT 1,Stato INTEGER NOT NULL DEFAULT 0,EntitaRiferimento TEXT,EntitaId TEXT,ResponsabileId TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,Status INTEGER NOT NULL DEFAULT 0);");}
public async Task<List<Scadenza>> GetAllAsync(int p,int ps,string? s,int? t,int? st){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Titolo LIKE @S)";if(t.HasValue)wh+=" AND Tipo=@T";if(st.HasValue)wh+=" AND Stato=@St";return(await c.QueryAsync<Scadenza>($"SELECT * FROM scadenze {wh} ORDER BY DataScadenza ASC LIMIT @PS OFFSET @O",new{S=$"%{s}%",T=t,St=st,PS=ps,O=(p-1)*ps})).ToList();}
public async Task<int> CountAsync(string? s,int? t,int? st){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Titolo LIKE @S)";if(t.HasValue)wh+=" AND Tipo=@T";if(st.HasValue)wh+=" AND Stato=@St";return await c.ExecuteScalarAsync<int>($"SELECT COUNT(*) FROM scadenze {wh}",new{S=$"%{s}%",T=t,St=st});}
public async Task<Scadenza?> GetByIdAsync(Guid id){using var c=C();return await c.QueryFirstOrDefaultAsync<Scadenza>("SELECT * FROM scadenze WHERE Id=@Id AND Status=0",new{Id=id.ToString()});}
public async Task<Scadenza> CreateAsync(Scadenza e){using var c=C();await c.ExecuteAsync("INSERT INTO scadenze(Id,Tipo,Titolo,Descrizione,DataScadenza,GiorniPreavviso,Priorita,Stato,EntitaRiferimento,EntitaId,ResponsabileId,CreatedAt,UpdatedAt,Status)VALUES(@Id,@Tipo,@Titolo,@Descrizione,@DataScadenza,@GiorniPreavviso,@Priorita,@Stato,@EntitaRiferimento,@EntitaId,@ResponsabileId,@CreatedAt,@UpdatedAt,@Status)",e);return e;}
public async Task<bool> UpdateAsync(Scadenza e){using var c=C();return await c.ExecuteAsync("UPDATE scadenze SET Tipo=@Tipo,Titolo=@Titolo,Descrizione=@Descrizione,DataScadenza=@DataScadenza,GiorniPreavviso=@GiorniPreavviso,Priorita=@Priorita,Stato=@Stato,EntitaRiferimento=@EntitaRiferimento,EntitaId=@EntitaId,ResponsabileId=@ResponsabileId,UpdatedAt=@UpdatedAt WHERE Id=@Id AND Status=0",e)>0;}
public async Task<bool> DeleteAsync(Guid id){using var c=C();return await c.ExecuteAsync("UPDATE scadenze SET Status=1,UpdatedAt=@N WHERE Id=@Id",new{Id=id.ToString(),N=DateTime.UtcNow})>0;}
public async Task<List<Scadenza>> GetProssimeAsync(int g){using var c=C();return(await c.QueryAsync<Scadenza>("SELECT * FROM scadenze WHERE Status=0 AND Stato IN(0,1) AND DataScadenza<=@S ORDER BY DataScadenza",new{S=DateTime.UtcNow.AddDays(g)})).ToList();}
public async Task<List<Scadenza>> GetPerMeseAsync(int a,int m){using var c=C();var i=new DateTime(a,m,1);return(await c.QueryAsync<Scadenza>("SELECT * FROM scadenze WHERE Status=0 AND DataScadenza>=@I AND DataScadenza<@F ORDER BY DataScadenza",new{I=i,F=i.AddMonths(1)})).ToList();}
public async Task<List<Scadenza>> GetPerResponsabileAsync(string rid){using var c=C();return(await c.QueryAsync<Scadenza>("SELECT * FROM scadenze WHERE Status=0 AND ResponsabileId=@R ORDER BY DataScadenza",new{R=rid})).ToList();}
public async Task<List<Scadenza>> GetAlertAsync(){using var c=C();return(await c.QueryAsync<Scadenza>("SELECT * FROM scadenze WHERE Status=0 AND Stato IN(0,1) ORDER BY DataScadenza")).ToList();}}
