using Dapper;using Microsoft.Data.Sqlite;using LEGAL.Compliance.Api.Models;
namespace LEGAL.Compliance.Api.Repositories;
public class ComplianceRepository{private readonly string _cs;public ComplianceRepository(string cs)=>_cs=cs;private SqliteConnection C()=>new(_cs);
public async Task InitializeAsync(){using var c=C();await c.OpenAsync();await c.ExecuteAsync("CREATE TABLE IF NOT EXISTS adempimenti(Id TEXT PRIMARY KEY,Normativa TEXT,Titolo TEXT NOT NULL,Descrizione TEXT,Tipo INTEGER NOT NULL,Frequenza INTEGER NOT NULL,Scadenza TEXT,Stato INTEGER NOT NULL DEFAULT 2,ResponsabileId TEXT,Note TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,Status INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS audit_compliance(Id TEXT PRIMARY KEY,AdempimentoId TEXT NOT NULL,DataAudit TEXT NOT NULL,Esito TEXT,Note TEXT,AuditorId TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,Status INTEGER NOT NULL DEFAULT 0);");}
public async Task<List<Adempimento>> GetAllAsync(int p,int ps,string? s,int? t,int? st){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Titolo LIKE @S OR Normativa LIKE @S)";if(t.HasValue)wh+=" AND Tipo=@T";if(st.HasValue)wh+=" AND Stato=@St";return(await c.QueryAsync<Adempimento>($"SELECT * FROM adempimenti {wh} ORDER BY Scadenza ASC LIMIT @PS OFFSET @O",new{S=$"%{s}%",T=t,St=st,PS=ps,O=(p-1)*ps})).ToList();}
public async Task<int> CountAsync(string? s,int? t,int? st){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Titolo LIKE @S)";if(t.HasValue)wh+=" AND Tipo=@T";if(st.HasValue)wh+=" AND Stato=@St";return await c.ExecuteScalarAsync<int>($"SELECT COUNT(*) FROM adempimenti {wh}",new{S=$"%{s}%",T=t,St=st});}
public async Task<Adempimento?> GetByIdAsync(Guid id){using var c=C();return await c.QueryFirstOrDefaultAsync<Adempimento>("SELECT * FROM adempimenti WHERE Id=@Id AND Status=0",new{Id=id.ToString()});}
public async Task<Adempimento> CreateAsync(Adempimento e){using var c=C();await c.ExecuteAsync("INSERT INTO adempimenti(Id,Normativa,Titolo,Descrizione,Tipo,Frequenza,Scadenza,Stato,ResponsabileId,Note,CreatedAt,UpdatedAt,Status)VALUES(@Id,@Normativa,@Titolo,@Descrizione,@Tipo,@Frequenza,@Scadenza,@Stato,@ResponsabileId,@Note,@CreatedAt,@UpdatedAt,@Status)",e);return e;}
public async Task<bool> UpdateAsync(Adempimento e){using var c=C();return await c.ExecuteAsync("UPDATE adempimenti SET Normativa=@Normativa,Titolo=@Titolo,Descrizione=@Descrizione,Tipo=@Tipo,Frequenza=@Frequenza,Scadenza=@Scadenza,Stato=@Stato,ResponsabileId=@ResponsabileId,Note=@Note,UpdatedAt=@UpdatedAt WHERE Id=@Id AND Status=0",e)>0;}
public async Task<bool> DeleteAsync(Guid id){using var c=C();return await c.ExecuteAsync("UPDATE adempimenti SET Status=1,UpdatedAt=@N WHERE Id=@Id",new{Id=id.ToString(),N=DateTime.UtcNow})>0;}
public async Task<object> GetDashboardAsync(){using var c=C();var t=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM adempimenti WHERE Status=0");var co=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM adempimenti WHERE Status=0 AND Stato=0");var nc=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM adempimenti WHERE Status=0 AND Stato=1");return new{Totale=t,Conformi=co,NonConformi=nc,PercentualeConformita=t>0?Math.Round((double)co/t*100,1):0};}
public async Task<List<Adempimento>> GetPerNormativaAsync(string n){using var c=C();return(await c.QueryAsync<Adempimento>("SELECT * FROM adempimenti WHERE Status=0 AND Normativa LIKE @N",new{N=$"%{n}%"})).ToList();}
public async Task<List<AuditCompliance>> GetAuditAsync(Guid aid){using var c=C();return(await c.QueryAsync<AuditCompliance>("SELECT * FROM audit_compliance WHERE AdempimentoId=@A AND Status=0 ORDER BY DataAudit DESC",new{A=aid.ToString()})).ToList();}
public async Task<AuditCompliance> CreateAuditAsync(AuditCompliance e){using var c=C();await c.ExecuteAsync("INSERT INTO audit_compliance(Id,AdempimentoId,DataAudit,Esito,Note,AuditorId,CreatedAt,UpdatedAt,Status)VALUES(@Id,@AdempimentoId,@DataAudit,@Esito,@Note,@AuditorId,@CreatedAt,@UpdatedAt,@Status)",e);return e;}}
