using LEGAL.Shared.Models;using LEGAL.Shared.Enums;
namespace LEGAL.Modello231.Api.Models;
public class ModelloOrganizzativo:BaseEntity{public int Versione{get;set;}=1;public string Titolo{get;set;}="";public DateTime? DataAdozione{get;set;}public DateTime? DataUltimaRevisione{get;set;}public string? ODV{get;set;}public StatoModello231 Stato{get;set;}=StatoModello231.Bozza;public string? Allegati{get;set;}}
public class AreaRischio231:BaseEntity{public Guid ModelloId{get;set;}public string Area{get;set;}="";public string Reato{get;set;}="";public TipoReato231 TipoReato{get;set;}public int Probabilita{get;set;}public int Impatto{get;set;}public LivelloRischio231 LivelloRischio{get;set;}public string? MisurePreventive{get;set;}public string? ProtocolliControllo{get;set;}public string? Responsabile{get;set;}public DateTime? UltimaValutazione{get;set;}}
public class Protocollo231:BaseEntity{public Guid AreaRischioId{get;set;}public string Nome{get;set;}="";public string? Descrizione{get;set;}public TipoProtocollo231 Tipo{get;set;}public FrequenzaProtocollo231 Frequenza{get;set;}public string? Responsabile{get;set;}public StatoProtocollo231 Stato{get;set;}=StatoProtocollo231.Attivo;public DateTime? UltimaVerifica{get;set;}}
public class FlussoInformativoODV:BaseEntity{public TipoFlussoODV Tipo{get;set;}public string? Segnalante{get;set;}public string? Descrizione{get;set;}public UrgenzaFlussoODV Urgenza{get;set;}public string? Allegati{get;set;}public StatoFlussoODV Stato{get;set;}=StatoFlussoODV.Ricevuto;public string? RispostaODV{get;set;}public DateTime? DataRisposta{get;set;}}
public class VerificaODV:BaseEntity{public Guid ProtocolloId{get;set;}public DateTime DataVerifica{get;set;}public string? Verificatore{get;set;}public EsitoVerificaODV Esito{get;set;}public string? Note{get;set;}public string? AzioniRichieste{get;set;}public DateTime? DataProssimaVerifica{get;set;}}
public class CreateModelloRequest{public int Versione{get;set;}=1;public string Titolo{get;set;}="";public DateTime? DataAdozione{get;set;}public DateTime? DataUltimaRevisione{get;set;}public string? ODV{get;set;}public StatoModello231 Stato{get;set;}public string? Allegati{get;set;}}
public class UpdateModelloRequest:CreateModelloRequest{}
public class CreateAreaRischioRequest{public Guid ModelloId{get;set;}public string Area{get;set;}="";public string Reato{get;set;}="";public TipoReato231 TipoReato{get;set;}public int Probabilita{get;set;}public int Impatto{get;set;}public LivelloRischio231 LivelloRischio{get;set;}public string? MisurePreventive{get;set;}public string? ProtocolliControllo{get;set;}public string? Responsabile{get;set;}public DateTime? UltimaValutazione{get;set;}}
public class UpdateAreaRischioRequest:CreateAreaRischioRequest{}
public class CreateProtocolloRequest{public Guid AreaRischioId{get;set;}public string Nome{get;set;}="";public string? Descrizione{get;set;}public TipoProtocollo231 Tipo{get;set;}public FrequenzaProtocollo231 Frequenza{get;set;}public string? Responsabile{get;set;}public StatoProtocollo231 Stato{get;set;}public DateTime? UltimaVerifica{get;set;}}
public class UpdateProtocolloRequest:CreateProtocolloRequest{}
public class CreateFlussoODVRequest{public TipoFlussoODV Tipo{get;set;}public string? Segnalante{get;set;}public string? Descrizione{get;set;}public UrgenzaFlussoODV Urgenza{get;set;}public string? Allegati{get;set;}public StatoFlussoODV Stato{get;set;}public string? RispostaODV{get;set;}public DateTime? DataRisposta{get;set;}}
public class UpdateFlussoODVRequest:CreateFlussoODVRequest{}
public class CreateVerificaODVRequest{public Guid ProtocolloId{get;set;}public DateTime DataVerifica{get;set;}public string? Verificatore{get;set;}public EsitoVerificaODV Esito{get;set;}public string? Note{get;set;}public string? AzioniRichieste{get;set;}public DateTime? DataProssimaVerifica{get;set;}}
public class EsaminaFlussoRequest{public string RispostaODV{get;set;}="";public StatoFlussoODV NuovoStato{get;set;}=StatoFlussoODV.Esaminato;}
