using Dapper;using Microsoft.Data.Sqlite;using LEGAL.Contenzioso.Api.Models;
namespace LEGAL.Contenzioso.Api.Repositories;
public class ContenziosoRepository{private readonly string _cs;public ContenziosoRepository(string cs)=>_cs=cs;private SqliteConnection C()=>new(_cs);
public async Task InitializeAsync(){using var c=C();await c.OpenAsync();await c.ExecuteAsync("CREATE TABLE IF NOT EXISTS contenziosi(Id TEXT PRIMARY KEY,Tipo INTEGER NOT NULL,Titolo TEXT NOT NULL,Descrizione TEXT,ControParte TEXT,ValoreControversia REAL,Stato INTEGER NOT NULL DEFAULT 0,DataApertura TEXT,DataChiusura TEXT,TribunaleCompetente TEXT,NumeroRuolo TEXT,AvvocatoRiferimento TEXT,Note TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,Status INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS atti_processuali(Id TEXT PRIMARY KEY,ContenziosoId TEXT NOT NULL,Tipo TEXT,Titolo TEXT NOT NULL,Data TEXT,FilePath TEXT,Note TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,Status INTEGER NOT NULL DEFAULT 0);");}
public async Task<List<CasoContenzioso>> GetAllAsync(int p,int ps,string? s,int? t,int? st){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Titolo LIKE @S OR ControParte LIKE @S)";if(t.HasValue)wh+=" AND Tipo=@T";if(st.HasValue)wh+=" AND Stato=@St";return(await c.QueryAsync<CasoContenzioso>($"SELECT * FROM contenziosi {wh} ORDER BY DataApertura DESC LIMIT @PS OFFSET @O",new{S=$"%{s}%",T=t,St=st,PS=ps,O=(p-1)*ps})).ToList();}
public async Task<int> CountAsync(string? s,int? t,int? st){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Titolo LIKE @S)";if(t.HasValue)wh+=" AND Tipo=@T";if(st.HasValue)wh+=" AND Stato=@St";return await c.ExecuteScalarAsync<int>($"SELECT COUNT(*) FROM contenziosi {wh}",new{S=$"%{s}%",T=t,St=st});}
public async Task<CasoContenzioso?> GetByIdAsync(Guid id){using var c=C();return await c.QueryFirstOrDefaultAsync<CasoContenzioso>("SELECT * FROM contenziosi WHERE Id=@Id AND Status=0",new{Id=id.ToString()});}
public async Task<CasoContenzioso> CreateAsync(CasoContenzioso e){using var c=C();await c.ExecuteAsync("INSERT INTO contenziosi(Id,Tipo,Titolo,Descrizione,ControParte,ValoreControversia,Stato,DataApertura,DataChiusura,TribunaleCompetente,NumeroRuolo,AvvocatoRiferimento,Note,CreatedAt,UpdatedAt,Status)VALUES(@Id,@Tipo,@Titolo,@Descrizione,@ControParte,@ValoreControversia,@Stato,@DataApertura,@DataChiusura,@TribunaleCompetente,@NumeroRuolo,@AvvocatoRiferimento,@Note,@CreatedAt,@UpdatedAt,@Status)",e);return e;}
public async Task<bool> UpdateAsync(CasoContenzioso e){using var c=C();return await c.ExecuteAsync("UPDATE contenziosi SET Tipo=@Tipo,Titolo=@Titolo,Descrizione=@Descrizione,ControParte=@ControParte,ValoreControversia=@ValoreControversia,Stato=@Stato,DataApertura=@DataApertura,DataChiusura=@DataChiusura,TribunaleCompetente=@TribunaleCompetente,NumeroRuolo=@NumeroRuolo,AvvocatoRiferimento=@AvvocatoRiferimento,Note=@Note,UpdatedAt=@UpdatedAt WHERE Id=@Id AND Status=0",e)>0;}
public async Task<bool> DeleteAsync(Guid id){using var c=C();return await c.ExecuteAsync("UPDATE contenziosi SET Status=1,UpdatedAt=@N WHERE Id=@Id",new{Id=id.ToString(),N=DateTime.UtcNow})>0;}
public async Task<object> GetStatisticheAsync(){using var c=C();var t=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM contenziosi WHERE Status=0");var ps=await c.QueryAsync("SELECT Stato,COUNT(*) as Ct FROM contenziosi WHERE Status=0 GROUP BY Stato");var v=await c.ExecuteScalarAsync<decimal?>("SELECT SUM(ValoreControversia) FROM contenziosi WHERE Status=0");return new{Totale=t,PerStato=ps,ValoreComplessivo=v??0};}
public async Task<List<AttoProcessuale>> GetAttiAsync(Guid cid){using var c=C();return(await c.QueryAsync<AttoProcessuale>("SELECT * FROM atti_processuali WHERE ContenziosoId=@CId AND Status=0 ORDER BY Data DESC",new{CId=cid.ToString()})).ToList();}
public async Task<AttoProcessuale> CreateAttoAsync(AttoProcessuale e){using var c=C();await c.ExecuteAsync("INSERT INTO atti_processuali(Id,ContenziosoId,Tipo,Titolo,Data,FilePath,Note,CreatedAt,UpdatedAt,Status)VALUES(@Id,@ContenziosoId,@Tipo,@Titolo,@Data,@FilePath,@Note,@CreatedAt,@UpdatedAt,@Status)",e);return e;}
public async Task<bool> DeleteAttoAsync(Guid id){using var c=C();return await c.ExecuteAsync("UPDATE atti_processuali SET Status=1,UpdatedAt=@N WHERE Id=@Id",new{Id=id.ToString(),N=DateTime.UtcNow})>0;}}
