using LEGAL.Contratti.Api.Models;using LEGAL.Contratti.Api.Repositories;using LEGAL.Shared.Models;
namespace LEGAL.Contratti.Api.Services;
public interface IContrattiService{Task<PagedResult<Contratto>> GetAllAsync(int p,int ps,string? s,int? t,int? st);Task<Contratto?> GetByIdAsync(Guid id);Task<Contratto> CreateAsync(CreateContrattoRequest r);Task<Contratto?> UpdateAsync(Guid id,UpdateContrattoRequest r);Task<bool> DeleteAsync(Guid id);Task<List<Contratto>> GetRinnoviInScadenzaAsync(int g);Task<List<Clausola>> GetClausoleAsync(Guid cid);Task<Clausola> CreateClausolaAsync(CreateClausolaRequest r);Task<bool> DeleteClausolaAsync(Guid id);Task<List<VersioneContratto>> GetVersioniAsync(Guid cid);Task<VersioneContratto> CreateVersioneAsync(CreateVersioneRequest r);Task<object> GetStatisticheAsync();}
public class ContrattiService:IContrattiService{private readonly ContrattiRepository _r;public ContrattiService(ContrattiRepository r)=>_r=r;
public async Task<PagedResult<Contratto>> GetAllAsync(int p,int ps,string? s,int? t,int? st){var items=await _r.GetAllAsync(p,ps,s,t,st);var total=await _r.CountAsync(s,t,st);return new PagedResult<Contratto>{Items=items,TotalCount=total,Page=p,PageSize=ps};}
public Task<Contratto?> GetByIdAsync(Guid id)=>_r.GetByIdAsync(id);
public async Task<Contratto> CreateAsync(CreateContrattoRequest r){var e=new Contratto{Tipo=r.Tipo,Titolo=r.Titolo,Descrizione=r.Descrizione,ControParte=r.ControParte,Valore=r.Valore,Valuta=r.Valuta,DataInizio=r.DataInizio,DataFine=r.DataFine,DataFirma=r.DataFirma,Stato=r.Stato,Rinnovo=r.Rinnovo,GiorniPreavviso=r.GiorniPreavviso,ResponsabileId=r.ResponsabileId,FilePath=r.FilePath,Note=r.Note,Tags=r.Tags};return await _r.CreateAsync(e);}
public async Task<Contratto?> UpdateAsync(Guid id,UpdateContrattoRequest r){var e=await _r.GetByIdAsync(id);if(e==null)return null;e.Tipo=r.Tipo;e.Titolo=r.Titolo;e.Descrizione=r.Descrizione;e.ControParte=r.ControParte;e.Valore=r.Valore;e.Valuta=r.Valuta;e.DataInizio=r.DataInizio;e.DataFine=r.DataFine;e.DataFirma=r.DataFirma;e.Stato=r.Stato;e.Rinnovo=r.Rinnovo;e.GiorniPreavviso=r.GiorniPreavviso;e.ResponsabileId=r.ResponsabileId;e.FilePath=r.FilePath;e.Note=r.Note;e.Tags=r.Tags;e.UpdatedAt=DateTime.UtcNow;await _r.UpdateAsync(e);return e;}
public Task<bool> DeleteAsync(Guid id)=>_r.DeleteAsync(id);public Task<List<Contratto>> GetRinnoviInScadenzaAsync(int g)=>_r.GetRinnoviInScadenzaAsync(g);public Task<List<Clausola>> GetClausoleAsync(Guid cid)=>_r.GetClausoleAsync(cid);
public async Task<Clausola> CreateClausolaAsync(CreateClausolaRequest r){var e=new Clausola{ContrattoId=r.ContrattoId,Titolo=r.Titolo,Testo=r.Testo,Tipo=r.Tipo,Ordine=r.Ordine};return await _r.CreateClausolaAsync(e);}
public Task<bool> DeleteClausolaAsync(Guid id)=>_r.DeleteClausolaAsync(id);public Task<List<VersioneContratto>> GetVersioniAsync(Guid cid)=>_r.GetVersioniAsync(cid);
public async Task<VersioneContratto> CreateVersioneAsync(CreateVersioneRequest r){var e=new VersioneContratto{ContrattoId=r.ContrattoId,FilePath=r.FilePath,Note=r.Note,CreatedBy=r.CreatedBy};return await _r.CreateVersioneAsync(e);}
public Task<object> GetStatisticheAsync()=>_r.GetStatisticheAsync();}
