using Dapper;using Microsoft.Data.Sqlite;using LEGAL.IP.Api.Models;
namespace LEGAL.IP.Api.Repositories;
public class IPRepository{private readonly string _cs;public IPRepository(string cs)=>_cs=cs;private SqliteConnection C()=>new(_cs);
public async Task InitializeAsync(){using var c=C();await c.OpenAsync();await c.ExecuteAsync("CREATE TABLE IF NOT EXISTS proprieta_intellettuali(Id TEXT PRIMARY KEY,Tipo INTEGER NOT NULL,Titolo TEXT NOT NULL,Descrizione TEXT,NumeroRegistrazione TEXT,Stato INTEGER NOT NULL DEFAULT 1,DataRegistrazione TEXT,DataScadenza TEXT,Territorio TEXT,Titolare TEXT,Note TEXT,Tags TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,Status INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS licenze_ip(Id TEXT PRIMARY KEY,IPId TEXT NOT NULL,Licenziatario TEXT,Tipo INTEGER NOT NULL DEFAULT 0,DataInizio TEXT,DataFine TEXT,Royalty REAL,Condizioni TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,Status INTEGER NOT NULL DEFAULT 0);");}
public async Task<List<ProprietaIntellettuale>> GetAllAsync(int p,int ps,string? s,int? t){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Titolo LIKE @S)";if(t.HasValue)wh+=" AND Tipo=@T";return(await c.QueryAsync<ProprietaIntellettuale>($"SELECT * FROM proprieta_intellettuali {wh} ORDER BY CreatedAt DESC LIMIT @PS OFFSET @O",new{S=$"%{s}%",T=t,PS=ps,O=(p-1)*ps})).ToList();}
public async Task<int> CountAsync(string? s,int? t){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Titolo LIKE @S)";if(t.HasValue)wh+=" AND Tipo=@T";return await c.ExecuteScalarAsync<int>($"SELECT COUNT(*) FROM proprieta_intellettuali {wh}",new{S=$"%{s}%",T=t});}
public async Task<ProprietaIntellettuale?> GetByIdAsync(Guid id){using var c=C();return await c.QueryFirstOrDefaultAsync<ProprietaIntellettuale>("SELECT * FROM proprieta_intellettuali WHERE Id=@Id AND Status=0",new{Id=id.ToString()});}
public async Task<ProprietaIntellettuale> CreateAsync(ProprietaIntellettuale e){using var c=C();await c.ExecuteAsync("INSERT INTO proprieta_intellettuali(Id,Tipo,Titolo,Descrizione,NumeroRegistrazione,Stato,DataRegistrazione,DataScadenza,Territorio,Titolare,Note,Tags,CreatedAt,UpdatedAt,Status)VALUES(@Id,@Tipo,@Titolo,@Descrizione,@NumeroRegistrazione,@Stato,@DataRegistrazione,@DataScadenza,@Territorio,@Titolare,@Note,@Tags,@CreatedAt,@UpdatedAt,@Status)",e);return e;}
public async Task<bool> UpdateAsync(ProprietaIntellettuale e){using var c=C();return await c.ExecuteAsync("UPDATE proprieta_intellettuali SET Tipo=@Tipo,Titolo=@Titolo,Descrizione=@Descrizione,NumeroRegistrazione=@NumeroRegistrazione,Stato=@Stato,DataRegistrazione=@DataRegistrazione,DataScadenza=@DataScadenza,Territorio=@Territorio,Titolare=@Titolare,Note=@Note,Tags=@Tags,UpdatedAt=@UpdatedAt WHERE Id=@Id AND Status=0",e)>0;}
public async Task<bool> DeleteAsync(Guid id){using var c=C();return await c.ExecuteAsync("UPDATE proprieta_intellettuali SET Status=1,UpdatedAt=@N WHERE Id=@Id",new{Id=id.ToString(),N=DateTime.UtcNow})>0;}
public async Task<List<ProprietaIntellettuale>> GetInScadenzaAsync(int g){using var c=C();return(await c.QueryAsync<ProprietaIntellettuale>("SELECT * FROM proprieta_intellettuali WHERE Status=0 AND DataScadenza IS NOT NULL AND DataScadenza<=@S ORDER BY DataScadenza",new{S=DateTime.UtcNow.AddDays(g)})).ToList();}
public async Task<List<LicenzaIP>> GetLicenzeAsync(Guid ipId){using var c=C();return(await c.QueryAsync<LicenzaIP>("SELECT * FROM licenze_ip WHERE IPId=@I AND Status=0",new{I=ipId.ToString()})).ToList();}
public async Task<LicenzaIP> CreateLicenzaAsync(LicenzaIP e){using var c=C();await c.ExecuteAsync("INSERT INTO licenze_ip(Id,IPId,Licenziatario,Tipo,DataInizio,DataFine,Royalty,Condizioni,CreatedAt,UpdatedAt,Status)VALUES(@Id,@IPId,@Licenziatario,@Tipo,@DataInizio,@DataFine,@Royalty,@Condizioni,@CreatedAt,@UpdatedAt,@Status)",e);return e;}
public async Task<bool> DeleteLicenzaAsync(Guid id){using var c=C();return await c.ExecuteAsync("UPDATE licenze_ip SET Status=1,UpdatedAt=@N WHERE Id=@Id",new{Id=id.ToString(),N=DateTime.UtcNow})>0;}
public async Task<object> GetStatisticheAsync(){using var c=C();var t=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM proprieta_intellettuali WHERE Status=0");return new{Totale=t};}}
