using LEGAL.Compliance.Api.Models;using LEGAL.Compliance.Api.Repositories;using LEGAL.Shared.Models;
namespace LEGAL.Compliance.Api.Services;
public interface IComplianceService{Task<PagedResult<Adempimento>> GetAllAsync(int p,int ps,string? s,int? t,int? st);Task<Adempimento?> GetByIdAsync(Guid id);Task<Adempimento> CreateAsync(CreateAdempimentoRequest r);Task<Adempimento?> UpdateAsync(Guid id,UpdateAdempimentoRequest r);Task<bool> DeleteAsync(Guid id);Task<object> GetDashboardAsync();Task<List<Adempimento>> GetPerNormativaAsync(string n);Task<List<AuditCompliance>> GetAuditAsync(Guid aid);Task<AuditCompliance> CreateAuditAsync(CreateAuditRequest r);}
public class ComplianceService:IComplianceService{private readonly ComplianceRepository _r;public ComplianceService(ComplianceRepository r)=>_r=r;
public async Task<PagedResult<Adempimento>> GetAllAsync(int p,int ps,string? s,int? t,int? st){var items=await _r.GetAllAsync(p,ps,s,t,st);var total=await _r.CountAsync(s,t,st);return new PagedResult<Adempimento>{Items=items,TotalCount=total,Page=p,PageSize=ps};}
public Task<Adempimento?> GetByIdAsync(Guid id)=>_r.GetByIdAsync(id);
public async Task<Adempimento> CreateAsync(CreateAdempimentoRequest r){var e=new Adempimento{Normativa=r.Normativa,Titolo=r.Titolo,Descrizione=r.Descrizione,Tipo=r.Tipo,Frequenza=r.Frequenza,Scadenza=r.Scadenza,Stato=r.Stato,ResponsabileId=r.ResponsabileId,Note=r.Note};return await _r.CreateAsync(e);}
public async Task<Adempimento?> UpdateAsync(Guid id,UpdateAdempimentoRequest r){var e=await _r.GetByIdAsync(id);if(e==null)return null;e.Normativa=r.Normativa;e.Titolo=r.Titolo;e.Descrizione=r.Descrizione;e.Tipo=r.Tipo;e.Frequenza=r.Frequenza;e.Scadenza=r.Scadenza;e.Stato=r.Stato;e.ResponsabileId=r.ResponsabileId;e.Note=r.Note;e.UpdatedAt=DateTime.UtcNow;await _r.UpdateAsync(e);return e;}
public Task<bool> DeleteAsync(Guid id)=>_r.DeleteAsync(id);public Task<object> GetDashboardAsync()=>_r.GetDashboardAsync();public Task<List<Adempimento>> GetPerNormativaAsync(string n)=>_r.GetPerNormativaAsync(n);public Task<List<AuditCompliance>> GetAuditAsync(Guid aid)=>_r.GetAuditAsync(aid);
public async Task<AuditCompliance> CreateAuditAsync(CreateAuditRequest r){var e=new AuditCompliance{AdempimentoId=r.AdempimentoId,DataAudit=r.DataAudit,Esito=r.Esito,Note=r.Note,AuditorId=r.AuditorId};return await _r.CreateAuditAsync(e);}}
