using LEGAL.IP.Api.Models;using LEGAL.IP.Api.Repositories;using LEGAL.Shared.Models;
namespace LEGAL.IP.Api.Services;
public interface IIPService{Task<PagedResult<ProprietaIntellettuale>> GetAllAsync(int p,int ps,string? s,int? t);Task<ProprietaIntellettuale?> GetByIdAsync(Guid id);Task<ProprietaIntellettuale> CreateAsync(CreateIPRequest r);Task<ProprietaIntellettuale?> UpdateAsync(Guid id,UpdateIPRequest r);Task<bool> DeleteAsync(Guid id);Task<List<ProprietaIntellettuale>> GetInScadenzaAsync(int g);Task<List<LicenzaIP>> GetLicenzeAsync(Guid ipId);Task<LicenzaIP> CreateLicenzaAsync(CreateLicenzaIPRequest r);Task<bool> DeleteLicenzaAsync(Guid id);Task<object> GetStatisticheAsync();}
public class IPService:IIPService{private readonly IPRepository _r;public IPService(IPRepository r)=>_r=r;
public async Task<PagedResult<ProprietaIntellettuale>> GetAllAsync(int p,int ps,string? s,int? t){var items=await _r.GetAllAsync(p,ps,s,t);var total=await _r.CountAsync(s,t);return new PagedResult<ProprietaIntellettuale>{Items=items,TotalCount=total,Page=p,PageSize=ps};}
public Task<ProprietaIntellettuale?> GetByIdAsync(Guid id)=>_r.GetByIdAsync(id);
public async Task<ProprietaIntellettuale> CreateAsync(CreateIPRequest r){var e=new ProprietaIntellettuale{Tipo=r.Tipo,Titolo=r.Titolo,Descrizione=r.Descrizione,NumeroRegistrazione=r.NumeroRegistrazione,Stato=r.Stato,DataRegistrazione=r.DataRegistrazione,DataScadenza=r.DataScadenza,Territorio=r.Territorio,Titolare=r.Titolare,Note=r.Note,Tags=r.Tags};return await _r.CreateAsync(e);}
public async Task<ProprietaIntellettuale?> UpdateAsync(Guid id,UpdateIPRequest r){var e=await _r.GetByIdAsync(id);if(e==null)return null;e.Tipo=r.Tipo;e.Titolo=r.Titolo;e.Descrizione=r.Descrizione;e.NumeroRegistrazione=r.NumeroRegistrazione;e.Stato=r.Stato;e.DataRegistrazione=r.DataRegistrazione;e.DataScadenza=r.DataScadenza;e.Territorio=r.Territorio;e.Titolare=r.Titolare;e.Note=r.Note;e.Tags=r.Tags;e.UpdatedAt=DateTime.UtcNow;await _r.UpdateAsync(e);return e;}
public Task<bool> DeleteAsync(Guid id)=>_r.DeleteAsync(id);public Task<List<ProprietaIntellettuale>> GetInScadenzaAsync(int g)=>_r.GetInScadenzaAsync(g);public Task<List<LicenzaIP>> GetLicenzeAsync(Guid ipId)=>_r.GetLicenzeAsync(ipId);
public async Task<LicenzaIP> CreateLicenzaAsync(CreateLicenzaIPRequest r){var e=new LicenzaIP{IPId=r.IPId,Licenziatario=r.Licenziatario,Tipo=r.Tipo,DataInizio=r.DataInizio,DataFine=r.DataFine,Royalty=r.Royalty,Condizioni=r.Condizioni};return await _r.CreateLicenzaAsync(e);}
public Task<bool> DeleteLicenzaAsync(Guid id)=>_r.DeleteLicenzaAsync(id);public Task<object> GetStatisticheAsync()=>_r.GetStatisticheAsync();}
