using Dapper;using Microsoft.Data.Sqlite;using LEGAL.Contratti.Api.Models;
namespace LEGAL.Contratti.Api.Repositories;
public class ContrattiRepository{private readonly string _cs;public ContrattiRepository(string cs)=>_cs=cs;private SqliteConnection C()=>new(_cs);
public async Task InitializeAsync(){using var c=C();await c.OpenAsync();await c.ExecuteAsync("CREATE TABLE IF NOT EXISTS contratti(Id TEXT PRIMARY KEY,Tipo INTEGER NOT NULL,Titolo TEXT NOT NULL,Descrizione TEXT,ControParte TEXT,Valore REAL,Valuta TEXT,DataInizio TEXT,DataFine TEXT,DataFirma TEXT,Stato INTEGER NOT NULL DEFAULT 0,Rinnovo INTEGER NOT NULL DEFAULT 2,GiorniPreavviso INTEGER DEFAULT 30,ResponsabileId TEXT,FilePath TEXT,Note TEXT,Tags TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,Status INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS clausole(Id TEXT PRIMARY KEY,ContrattoId TEXT NOT NULL,Titolo TEXT NOT NULL,Testo TEXT,Tipo INTEGER NOT NULL DEFAULT 0,Ordine INTEGER DEFAULT 0,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,Status INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS versioni_contratto(Id TEXT PRIMARY KEY,ContrattoId TEXT NOT NULL,Versione INTEGER NOT NULL,FilePath TEXT,Note TEXT,CreatedBy TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,Status INTEGER NOT NULL DEFAULT 0);");}
public async Task<List<Contratto>> GetAllAsync(int p,int ps,string? s,int? t,int? st){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Titolo LIKE @S OR ControParte LIKE @S)";if(t.HasValue)wh+=" AND Tipo=@T";if(st.HasValue)wh+=" AND Stato=@St";return(await c.QueryAsync<Contratto>($"SELECT * FROM contratti {wh} ORDER BY CreatedAt DESC LIMIT @PS OFFSET @O",new{S=$"%{s}%",T=t,St=st,PS=ps,O=(p-1)*ps})).ToList();}
public async Task<int> CountAsync(string? s,int? t,int? st){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Titolo LIKE @S)";if(t.HasValue)wh+=" AND Tipo=@T";if(st.HasValue)wh+=" AND Stato=@St";return await c.ExecuteScalarAsync<int>($"SELECT COUNT(*) FROM contratti {wh}",new{S=$"%{s}%",T=t,St=st});}
public async Task<Contratto?> GetByIdAsync(Guid id){using var c=C();return await c.QueryFirstOrDefaultAsync<Contratto>("SELECT * FROM contratti WHERE Id=@Id AND Status=0",new{Id=id.ToString()});}
public async Task<Contratto> CreateAsync(Contratto e){using var c=C();await c.ExecuteAsync("INSERT INTO contratti(Id,Tipo,Titolo,Descrizione,ControParte,Valore,Valuta,DataInizio,DataFine,DataFirma,Stato,Rinnovo,GiorniPreavviso,ResponsabileId,FilePath,Note,Tags,CreatedAt,UpdatedAt,Status)VALUES(@Id,@Tipo,@Titolo,@Descrizione,@ControParte,@Valore,@Valuta,@DataInizio,@DataFine,@DataFirma,@Stato,@Rinnovo,@GiorniPreavviso,@ResponsabileId,@FilePath,@Note,@Tags,@CreatedAt,@UpdatedAt,@Status)",e);return e;}
public async Task<bool> UpdateAsync(Contratto e){using var c=C();return await c.ExecuteAsync("UPDATE contratti SET Tipo=@Tipo,Titolo=@Titolo,Descrizione=@Descrizione,ControParte=@ControParte,Valore=@Valore,Valuta=@Valuta,DataInizio=@DataInizio,DataFine=@DataFine,DataFirma=@DataFirma,Stato=@Stato,Rinnovo=@Rinnovo,GiorniPreavviso=@GiorniPreavviso,ResponsabileId=@ResponsabileId,FilePath=@FilePath,Note=@Note,Tags=@Tags,UpdatedAt=@UpdatedAt WHERE Id=@Id AND Status=0",e)>0;}
public async Task<bool> DeleteAsync(Guid id){using var c=C();return await c.ExecuteAsync("UPDATE contratti SET Status=1,UpdatedAt=@N WHERE Id=@Id",new{Id=id.ToString(),N=DateTime.UtcNow})>0;}
public async Task<List<Contratto>> GetRinnoviInScadenzaAsync(int g){using var c=C();return(await c.QueryAsync<Contratto>("SELECT * FROM contratti WHERE Status=0 AND Stato IN(2,3) AND DataFine IS NOT NULL AND DataFine<=@S ORDER BY DataFine",new{S=DateTime.UtcNow.AddDays(g)})).ToList();}
public async Task<List<Clausola>> GetClausoleAsync(Guid cid){using var c=C();return(await c.QueryAsync<Clausola>("SELECT * FROM clausole WHERE ContrattoId=@CId AND Status=0 ORDER BY Ordine",new{CId=cid.ToString()})).ToList();}
public async Task<Clausola> CreateClausolaAsync(Clausola e){using var c=C();await c.ExecuteAsync("INSERT INTO clausole(Id,ContrattoId,Titolo,Testo,Tipo,Ordine,CreatedAt,UpdatedAt,Status)VALUES(@Id,@ContrattoId,@Titolo,@Testo,@Tipo,@Ordine,@CreatedAt,@UpdatedAt,@Status)",e);return e;}
public async Task<bool> DeleteClausolaAsync(Guid id){using var c=C();return await c.ExecuteAsync("UPDATE clausole SET Status=1,UpdatedAt=@N WHERE Id=@Id",new{Id=id.ToString(),N=DateTime.UtcNow})>0;}
public async Task<List<VersioneContratto>> GetVersioniAsync(Guid cid){using var c=C();return(await c.QueryAsync<VersioneContratto>("SELECT * FROM versioni_contratto WHERE ContrattoId=@CId AND Status=0 ORDER BY Versione DESC",new{CId=cid.ToString()})).ToList();}
public async Task<VersioneContratto> CreateVersioneAsync(VersioneContratto e){using var c=C();var mx=await c.ExecuteScalarAsync<int?>("SELECT MAX(Versione) FROM versioni_contratto WHERE ContrattoId=@CId AND Status=0",new{CId=e.ContrattoId.ToString()});e.Versione=(mx??0)+1;await c.ExecuteAsync("INSERT INTO versioni_contratto(Id,ContrattoId,Versione,FilePath,Note,CreatedBy,CreatedAt,UpdatedAt,Status)VALUES(@Id,@ContrattoId,@Versione,@FilePath,@Note,@CreatedBy,@CreatedAt,@UpdatedAt,@Status)",e);return e;}
public async Task<object> GetStatisticheAsync(){using var c=C();var t=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM contratti WHERE Status=0");var ps=await c.QueryAsync("SELECT Stato,COUNT(*) as Ct FROM contratti WHERE Status=0 GROUP BY Stato");var pt=await c.QueryAsync("SELECT Tipo,COUNT(*) as Ct FROM contratti WHERE Status=0 GROUP BY Tipo");var v=await c.ExecuteScalarAsync<decimal?>("SELECT SUM(Valore) FROM contratti WHERE Status=0");return new{Totale=t,PerStato=ps,PerTipo=pt,ValoreComplessivo=v??0};}}
