using LEGAL.Contenzioso.Api.Models;using LEGAL.Contenzioso.Api.Repositories;using LEGAL.Shared.Models;
namespace LEGAL.Contenzioso.Api.Services;
public interface IContenziosoService{Task<PagedResult<Contenzioso>> GetAllAsync(int p,int ps,string? s,int? t,int? st);Task<Contenzioso?> GetByIdAsync(Guid id);Task<Contenzioso> CreateAsync(CreateContenziosoRequest r);Task<Contenzioso?> UpdateAsync(Guid id,UpdateContenziosoRequest r);Task<bool> DeleteAsync(Guid id);Task<object> GetStatisticheAsync();Task<List<AttoProcessuale>> GetAttiAsync(Guid cid);Task<AttoProcessuale> CreateAttoAsync(CreateAttoRequest r);Task<bool> DeleteAttoAsync(Guid id);}
public class ContenziosoService:IContenziosoService{private readonly ContenziosoRepository _r;public ContenziosoService(ContenziosoRepository r)=>_r=r;
public async Task<PagedResult<Contenzioso>> GetAllAsync(int p,int ps,string? s,int? t,int? st){var items=await _r.GetAllAsync(p,ps,s,t,st);var total=await _r.CountAsync(s,t,st);return new PagedResult<Contenzioso>{Items=items,TotalCount=total,Page=p,PageSize=ps};}
public Task<Contenzioso?> GetByIdAsync(Guid id)=>_r.GetByIdAsync(id);
public async Task<Contenzioso> CreateAsync(CreateContenziosoRequest r){var e=new Contenzioso{Tipo=r.Tipo,Titolo=r.Titolo,Descrizione=r.Descrizione,ControParte=r.ControParte,ValoreControversia=r.ValoreControversia,Stato=r.Stato,DataApertura=r.DataApertura,DataChiusura=r.DataChiusura,TribunaleCompetente=r.TribunaleCompetente,NumeroRuolo=r.NumeroRuolo,AvvocatoRiferimento=r.AvvocatoRiferimento,Note=r.Note};return await _r.CreateAsync(e);}
public async Task<Contenzioso?> UpdateAsync(Guid id,UpdateContenziosoRequest r){var e=await _r.GetByIdAsync(id);if(e==null)return null;e.Tipo=r.Tipo;e.Titolo=r.Titolo;e.Descrizione=r.Descrizione;e.ControParte=r.ControParte;e.ValoreControversia=r.ValoreControversia;e.Stato=r.Stato;e.DataApertura=r.DataApertura;e.DataChiusura=r.DataChiusura;e.TribunaleCompetente=r.TribunaleCompetente;e.NumeroRuolo=r.NumeroRuolo;e.AvvocatoRiferimento=r.AvvocatoRiferimento;e.Note=r.Note;e.UpdatedAt=DateTime.UtcNow;await _r.UpdateAsync(e);return e;}
public Task<bool> DeleteAsync(Guid id)=>_r.DeleteAsync(id);public Task<object> GetStatisticheAsync()=>_r.GetStatisticheAsync();public Task<List<AttoProcessuale>> GetAttiAsync(Guid cid)=>_r.GetAttiAsync(cid);
public async Task<AttoProcessuale> CreateAttoAsync(CreateAttoRequest r){var e=new AttoProcessuale{ContenziosoId=r.ContenziosoId,Tipo=r.Tipo,Titolo=r.Titolo,Data=r.Data,FilePath=r.FilePath,Note=r.Note};return await _r.CreateAttoAsync(e);}
public Task<bool> DeleteAttoAsync(Guid id)=>_r.DeleteAttoAsync(id);}
