using Dapper;using Microsoft.Data.Sqlite;using LEGAL.Modello231.Api.Models;
namespace LEGAL.Modello231.Api.Repositories;
public class Modello231Repository{private readonly string _cs;public Modello231Repository(string cs)=>_cs=cs;private SqliteConnection C()=>new(_cs);
public async Task InitializeAsync(){using var c=C();await c.OpenAsync();await c.ExecuteAsync(@"
CREATE TABLE IF NOT EXISTS modello_organizzativo(Id TEXT PRIMARY KEY,Versione INTEGER NOT NULL DEFAULT 1,Titolo TEXT NOT NULL,DataAdozione TEXT,DataUltimaRevisione TEXT,ODV TEXT,Stato INTEGER NOT NULL DEFAULT 0,Allegati TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,Status INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS aree_rischio_231(Id TEXT PRIMARY KEY,ModelloId TEXT NOT NULL,Area TEXT NOT NULL,Reato TEXT NOT NULL,TipoReato INTEGER NOT NULL,Probabilita INTEGER NOT NULL,Impatto INTEGER NOT NULL,LivelloRischio INTEGER NOT NULL,MisurePreventive TEXT,ProtocolliControllo TEXT,Responsabile TEXT,UltimaValutazione TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,Status INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS protocolli_231(Id TEXT PRIMARY KEY,AreaRischioId TEXT NOT NULL,Nome TEXT NOT NULL,Descrizione TEXT,Tipo INTEGER NOT NULL,Frequenza INTEGER NOT NULL,Responsabile TEXT,Stato INTEGER NOT NULL DEFAULT 0,UltimaVerifica TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,Status INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS flussi_informativi_odv(Id TEXT PRIMARY KEY,Tipo INTEGER NOT NULL,Segnalante TEXT,Descrizione TEXT,Urgenza INTEGER NOT NULL DEFAULT 0,Allegati TEXT,Stato INTEGER NOT NULL DEFAULT 0,RispostaODV TEXT,DataRisposta TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,Status INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS verifiche_odv(Id TEXT PRIMARY KEY,ProtocolloId TEXT NOT NULL,DataVerifica TEXT NOT NULL,Verificatore TEXT,Esito INTEGER NOT NULL,Note TEXT,AzioniRichieste TEXT,DataProssimaVerifica TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,Status INTEGER NOT NULL DEFAULT 0);");}
// === Modello Organizzativo ===
public async Task<List<ModelloOrganizzativo>> GetModelliAsync(int p,int ps,string? s,int? stato){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Titolo LIKE @S OR ODV LIKE @S)";if(stato.HasValue)wh+=" AND Stato=@St";return(await c.QueryAsync<ModelloOrganizzativo>($"SELECT * FROM modello_organizzativo {wh} ORDER BY Versione DESC LIMIT @PS OFFSET @O",new{S=$"%{s}%",St=stato,PS=ps,O=(p-1)*ps})).ToList();}
public async Task<int> CountModelliAsync(string? s,int? stato){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Titolo LIKE @S)";if(stato.HasValue)wh+=" AND Stato=@St";return await c.ExecuteScalarAsync<int>($"SELECT COUNT(*) FROM modello_organizzativo {wh}",new{S=$"%{s}%",St=stato});}
public async Task<ModelloOrganizzativo?> GetModelloByIdAsync(Guid id){using var c=C();return await c.QueryFirstOrDefaultAsync<ModelloOrganizzativo>("SELECT * FROM modello_organizzativo WHERE Id=@Id AND Status=0",new{Id=id.ToString()});}
public async Task<ModelloOrganizzativo?> GetModelloVigenteAsync(){using var c=C();return await c.QueryFirstOrDefaultAsync<ModelloOrganizzativo>("SELECT * FROM modello_organizzativo WHERE Status=0 AND Stato=1 ORDER BY Versione DESC LIMIT 1");}
public async Task<ModelloOrganizzativo> CreateModelloAsync(ModelloOrganizzativo e){using var c=C();await c.ExecuteAsync("INSERT INTO modello_organizzativo(Id,Versione,Titolo,DataAdozione,DataUltimaRevisione,ODV,Stato,Allegati,CreatedAt,UpdatedAt,Status)VALUES(@Id,@Versione,@Titolo,@DataAdozione,@DataUltimaRevisione,@ODV,@Stato,@Allegati,@CreatedAt,@UpdatedAt,@Status)",e);return e;}
public async Task<bool> UpdateModelloAsync(ModelloOrganizzativo e){using var c=C();return await c.ExecuteAsync("UPDATE modello_organizzativo SET Versione=@Versione,Titolo=@Titolo,DataAdozione=@DataAdozione,DataUltimaRevisione=@DataUltimaRevisione,ODV=@ODV,Stato=@Stato,Allegati=@Allegati,UpdatedAt=@UpdatedAt WHERE Id=@Id AND Status=0",e)>0;}
public async Task<bool> DeleteModelloAsync(Guid id){using var c=C();return await c.ExecuteAsync("UPDATE modello_organizzativo SET Status=1,UpdatedAt=@N WHERE Id=@Id",new{Id=id.ToString(),N=DateTime.UtcNow})>0;}
// === Aree Rischio ===
public async Task<List<AreaRischio231>> GetAreeRischioAsync(int p,int ps,string? s,int? tipo){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Area LIKE @S OR Reato LIKE @S)";if(tipo.HasValue)wh+=" AND TipoReato=@T";return(await c.QueryAsync<AreaRischio231>($"SELECT * FROM aree_rischio_231 {wh} ORDER BY LivelloRischio DESC LIMIT @PS OFFSET @O",new{S=$"%{s}%",T=tipo,PS=ps,O=(p-1)*ps})).ToList();}
public async Task<int> CountAreeRischioAsync(string? s,int? tipo){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Area LIKE @S)";if(tipo.HasValue)wh+=" AND TipoReato=@T";return await c.ExecuteScalarAsync<int>($"SELECT COUNT(*) FROM aree_rischio_231 {wh}",new{S=$"%{s}%",T=tipo});}
public async Task<AreaRischio231?> GetAreaRischioByIdAsync(Guid id){using var c=C();return await c.QueryFirstOrDefaultAsync<AreaRischio231>("SELECT * FROM aree_rischio_231 WHERE Id=@Id AND Status=0",new{Id=id.ToString()});}
public async Task<List<AreaRischio231>> GetAreeRischioMatriceAsync(){using var c=C();return(await c.QueryAsync<AreaRischio231>("SELECT * FROM aree_rischio_231 WHERE Status=0 ORDER BY LivelloRischio DESC,Probabilita DESC,Impatto DESC")).ToList();}
public async Task<List<AreaRischio231>> GetAreeRischioCriticheAsync(){using var c=C();return(await c.QueryAsync<AreaRischio231>("SELECT * FROM aree_rischio_231 WHERE Status=0 AND LivelloRischio>=2 ORDER BY LivelloRischio DESC")).ToList();}
public async Task<AreaRischio231> CreateAreaRischioAsync(AreaRischio231 e){using var c=C();await c.ExecuteAsync("INSERT INTO aree_rischio_231(Id,ModelloId,Area,Reato,TipoReato,Probabilita,Impatto,LivelloRischio,MisurePreventive,ProtocolliControllo,Responsabile,UltimaValutazione,CreatedAt,UpdatedAt,Status)VALUES(@Id,@ModelloId,@Area,@Reato,@TipoReato,@Probabilita,@Impatto,@LivelloRischio,@MisurePreventive,@ProtocolliControllo,@Responsabile,@UltimaValutazione,@CreatedAt,@UpdatedAt,@Status)",e);return e;}
public async Task<bool> UpdateAreaRischioAsync(AreaRischio231 e){using var c=C();return await c.ExecuteAsync("UPDATE aree_rischio_231 SET ModelloId=@ModelloId,Area=@Area,Reato=@Reato,TipoReato=@TipoReato,Probabilita=@Probabilita,Impatto=@Impatto,LivelloRischio=@LivelloRischio,MisurePreventive=@MisurePreventive,ProtocolliControllo=@ProtocolliControllo,Responsabile=@Responsabile,UltimaValutazione=@UltimaValutazione,UpdatedAt=@UpdatedAt WHERE Id=@Id AND Status=0",e)>0;}
public async Task<bool> DeleteAreaRischioAsync(Guid id){using var c=C();return await c.ExecuteAsync("UPDATE aree_rischio_231 SET Status=1,UpdatedAt=@N WHERE Id=@Id",new{Id=id.ToString(),N=DateTime.UtcNow})>0;}
// === Protocolli ===
public async Task<List<Protocollo231>> GetProtocolliAsync(int p,int ps,string? s,int? tipo){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Nome LIKE @S OR Descrizione LIKE @S)";if(tipo.HasValue)wh+=" AND Tipo=@T";return(await c.QueryAsync<Protocollo231>($"SELECT * FROM protocolli_231 {wh} ORDER BY CreatedAt DESC LIMIT @PS OFFSET @O",new{S=$"%{s}%",T=tipo,PS=ps,O=(p-1)*ps})).ToList();}
public async Task<int> CountProtocolliAsync(string? s,int? tipo){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Nome LIKE @S)";if(tipo.HasValue)wh+=" AND Tipo=@T";return await c.ExecuteScalarAsync<int>($"SELECT COUNT(*) FROM protocolli_231 {wh}",new{S=$"%{s}%",T=tipo});}
public async Task<Protocollo231?> GetProtocolloByIdAsync(Guid id){using var c=C();return await c.QueryFirstOrDefaultAsync<Protocollo231>("SELECT * FROM protocolli_231 WHERE Id=@Id AND Status=0",new{Id=id.ToString()});}
public async Task<List<Protocollo231>> GetProtocolliScadutiAsync(){using var c=C();return(await c.QueryAsync<Protocollo231>("SELECT * FROM protocolli_231 WHERE Status=0 AND UltimaVerifica IS NOT NULL AND UltimaVerifica < @D ORDER BY UltimaVerifica ASC",new{D=DateTime.UtcNow.AddDays(-90).ToString("o")})).ToList();}
public async Task<List<Protocollo231>> GetProtocolliByAreaAsync(Guid areaId){using var c=C();return(await c.QueryAsync<Protocollo231>("SELECT * FROM protocolli_231 WHERE Status=0 AND AreaRischioId=@A ORDER BY Nome",new{A=areaId.ToString()})).ToList();}
public async Task<Protocollo231> CreateProtocolloAsync(Protocollo231 e){using var c=C();await c.ExecuteAsync("INSERT INTO protocolli_231(Id,AreaRischioId,Nome,Descrizione,Tipo,Frequenza,Responsabile,Stato,UltimaVerifica,CreatedAt,UpdatedAt,Status)VALUES(@Id,@AreaRischioId,@Nome,@Descrizione,@Tipo,@Frequenza,@Responsabile,@Stato,@UltimaVerifica,@CreatedAt,@UpdatedAt,@Status)",e);return e;}
public async Task<bool> UpdateProtocolloAsync(Protocollo231 e){using var c=C();return await c.ExecuteAsync("UPDATE protocolli_231 SET AreaRischioId=@AreaRischioId,Nome=@Nome,Descrizione=@Descrizione,Tipo=@Tipo,Frequenza=@Frequenza,Responsabile=@Responsabile,Stato=@Stato,UltimaVerifica=@UltimaVerifica,UpdatedAt=@UpdatedAt WHERE Id=@Id AND Status=0",e)>0;}
public async Task<bool> DeleteProtocolloAsync(Guid id){using var c=C();return await c.ExecuteAsync("UPDATE protocolli_231 SET Status=1,UpdatedAt=@N WHERE Id=@Id",new{Id=id.ToString(),N=DateTime.UtcNow})>0;}
// === Flussi Informativi ODV ===
public async Task<List<FlussoInformativoODV>> GetFlussiAsync(int p,int ps,string? s,int? tipo){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Descrizione LIKE @S OR Segnalante LIKE @S)";if(tipo.HasValue)wh+=" AND Tipo=@T";return(await c.QueryAsync<FlussoInformativoODV>($"SELECT * FROM flussi_informativi_odv {wh} ORDER BY CreatedAt DESC LIMIT @PS OFFSET @O",new{S=$"%{s}%",T=tipo,PS=ps,O=(p-1)*ps})).ToList();}
public async Task<int> CountFlussiAsync(string? s,int? tipo){using var c=C();var wh="WHERE Status=0";if(!string.IsNullOrEmpty(s))wh+=" AND(Descrizione LIKE @S)";if(tipo.HasValue)wh+=" AND Tipo=@T";return await c.ExecuteScalarAsync<int>($"SELECT COUNT(*) FROM flussi_informativi_odv {wh}",new{S=$"%{s}%",T=tipo});}
public async Task<FlussoInformativoODV?> GetFlussoByIdAsync(Guid id){using var c=C();return await c.QueryFirstOrDefaultAsync<FlussoInformativoODV>("SELECT * FROM flussi_informativi_odv WHERE Id=@Id AND Status=0",new{Id=id.ToString()});}
public async Task<List<FlussoInformativoODV>> GetFlussiInEsameAsync(){using var c=C();return(await c.QueryAsync<FlussoInformativoODV>("SELECT * FROM flussi_informativi_odv WHERE Status=0 AND Stato=1 ORDER BY Urgenza DESC,CreatedAt ASC")).ToList();}
public async Task<FlussoInformativoODV> CreateFlussoAsync(FlussoInformativoODV e){using var c=C();await c.ExecuteAsync("INSERT INTO flussi_informativi_odv(Id,Tipo,Segnalante,Descrizione,Urgenza,Allegati,Stato,RispostaODV,DataRisposta,CreatedAt,UpdatedAt,Status)VALUES(@Id,@Tipo,@Segnalante,@Descrizione,@Urgenza,@Allegati,@Stato,@RispostaODV,@DataRisposta,@CreatedAt,@UpdatedAt,@Status)",e);return e;}
public async Task<bool> UpdateFlussoAsync(FlussoInformativoODV e){using var c=C();return await c.ExecuteAsync("UPDATE flussi_informativi_odv SET Tipo=@Tipo,Segnalante=@Segnalante,Descrizione=@Descrizione,Urgenza=@Urgenza,Allegati=@Allegati,Stato=@Stato,RispostaODV=@RispostaODV,DataRisposta=@DataRisposta,UpdatedAt=@UpdatedAt WHERE Id=@Id AND Status=0",e)>0;}
public async Task<bool> DeleteFlussoAsync(Guid id){using var c=C();return await c.ExecuteAsync("UPDATE flussi_informativi_odv SET Status=1,UpdatedAt=@N WHERE Id=@Id",new{Id=id.ToString(),N=DateTime.UtcNow})>0;}
// === Verifiche ODV ===
public async Task<List<VerificaODV>> GetVerificheAsync(int p,int ps){using var c=C();return(await c.QueryAsync<VerificaODV>("SELECT * FROM verifiche_odv WHERE Status=0 ORDER BY DataVerifica DESC LIMIT @PS OFFSET @O",new{PS=ps,O=(p-1)*ps})).ToList();}
public async Task<int> CountVerificheAsync(){using var c=C();return await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM verifiche_odv WHERE Status=0");}
public async Task<VerificaODV?> GetVerificaByIdAsync(Guid id){using var c=C();return await c.QueryFirstOrDefaultAsync<VerificaODV>("SELECT * FROM verifiche_odv WHERE Id=@Id AND Status=0",new{Id=id.ToString()});}
public async Task<List<VerificaODV>> GetVerificheProssimeAsync(){using var c=C();return(await c.QueryAsync<VerificaODV>("SELECT * FROM verifiche_odv WHERE Status=0 AND DataProssimaVerifica IS NOT NULL AND DataProssimaVerifica >= @D ORDER BY DataProssimaVerifica ASC LIMIT 20",new{D=DateTime.UtcNow.ToString("o")})).ToList();}
public async Task<List<VerificaODV>> GetVerificheNonConformiAsync(){using var c=C();return(await c.QueryAsync<VerificaODV>("SELECT * FROM verifiche_odv WHERE Status=0 AND Esito=1 ORDER BY DataVerifica DESC")).ToList();}
public async Task<VerificaODV> CreateVerificaAsync(VerificaODV e){using var c=C();await c.ExecuteAsync("INSERT INTO verifiche_odv(Id,ProtocolloId,DataVerifica,Verificatore,Esito,Note,AzioniRichieste,DataProssimaVerifica,CreatedAt,UpdatedAt,Status)VALUES(@Id,@ProtocolloId,@DataVerifica,@Verificatore,@Esito,@Note,@AzioniRichieste,@DataProssimaVerifica,@CreatedAt,@UpdatedAt,@Status)",e);return e;}
public async Task<bool> DeleteVerificaAsync(Guid id){using var c=C();return await c.ExecuteAsync("UPDATE verifiche_odv SET Status=1,UpdatedAt=@N WHERE Id=@Id",new{Id=id.ToString(),N=DateTime.UtcNow})>0;}
// === Dashboard ===
public async Task<object> GetDashboardAsync(){using var c=C();var areeT=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM aree_rischio_231 WHERE Status=0");var areeCrit=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM aree_rischio_231 WHERE Status=0 AND LivelloRischio>=2");var protT=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM protocolli_231 WHERE Status=0");var protScad=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM protocolli_231 WHERE Status=0 AND UltimaVerifica IS NOT NULL AND UltimaVerifica < @D",new{D=DateTime.UtcNow.AddDays(-90).ToString("o")});var flussiAperti=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM flussi_informativi_odv WHERE Status=0 AND Stato IN(0,1)");var verNonConf=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM verifiche_odv WHERE Status=0 AND Esito=1");var verPross=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM verifiche_odv WHERE Status=0 AND DataProssimaVerifica IS NOT NULL AND DataProssimaVerifica >= @D AND DataProssimaVerifica <= @D2",new{D=DateTime.UtcNow.ToString("o"),D2=DateTime.UtcNow.AddDays(30).ToString("o")});return new{AreeRischioTotali=areeT,AreeRischioCritiche=areeCrit,ProtocolliTotali=protT,ProtocolliScaduti=protScad,FlussiAperti=flussiAperti,VerificheNonConformi=verNonConf,VerificheProssimi30Giorni=verPross};}}
