using LEGAL.Shared.Models;using LEGAL.Shared.Enums;
namespace LEGAL.Contratti.Api.Models;
public class Contratto:BaseEntity{public TipoContratto Tipo{get;set;}public string Titolo{get;set;}="";public string? Descrizione{get;set;}public string? ControParte{get;set;}public decimal? Valore{get;set;}public string? Valuta{get;set;}="EUR";public DateTime? DataInizio{get;set;}public DateTime? DataFine{get;set;}public DateTime? DataFirma{get;set;}public StatoContratto Stato{get;set;}=StatoContratto.Bozza;public TipoRinnovo Rinnovo{get;set;}=TipoRinnovo.No;public int GiorniPreavviso{get;set;}=30;public string? ResponsabileId{get;set;}public string? FilePath{get;set;}public string? Note{get;set;}public string? Tags{get;set;}}
public class Clausola:BaseEntity{public Guid ContrattoId{get;set;}public string Titolo{get;set;}="";public string? Testo{get;set;}public TipoClausola Tipo{get;set;}=TipoClausola.Standard;public int Ordine{get;set;}}
public class VersioneContratto:BaseEntity{public Guid ContrattoId{get;set;}public int Versione{get;set;}public string? FilePath{get;set;}public string? Note{get;set;}public string? CreatedBy{get;set;}}
public class CreateContrattoRequest{public TipoContratto Tipo{get;set;}public string Titolo{get;set;}="";public string? Descrizione{get;set;}public string? ControParte{get;set;}public decimal? Valore{get;set;}public string? Valuta{get;set;}="EUR";public DateTime? DataInizio{get;set;}public DateTime? DataFine{get;set;}public DateTime? DataFirma{get;set;}public StatoContratto Stato{get;set;}public TipoRinnovo Rinnovo{get;set;}public int GiorniPreavviso{get;set;}=30;public string? ResponsabileId{get;set;}public string? FilePath{get;set;}public string? Note{get;set;}public string? Tags{get;set;}}
public class UpdateContrattoRequest:CreateContrattoRequest{}
public class CreateClausolaRequest{public Guid ContrattoId{get;set;}public string Titolo{get;set;}="";public string? Testo{get;set;}public TipoClausola Tipo{get;set;}public int Ordine{get;set;}}
public class CreateVersioneRequest{public Guid ContrattoId{get;set;}public string? FilePath{get;set;}public string? Note{get;set;}public string? CreatedBy{get;set;}}
