using LEGAL.Scadenze.Api.Models;using LEGAL.Scadenze.Api.Repositories;using LEGAL.Shared.Models;
namespace LEGAL.Scadenze.Api.Services;
public interface IScadenzeService{Task<PagedResult<Scadenza>> GetAllAsync(int p,int ps,string? s,int? t,int? st);Task<Scadenza?> GetByIdAsync(Guid id);Task<Scadenza> CreateAsync(CreateScadenzaRequest r);Task<Scadenza?> UpdateAsync(Guid id,UpdateScadenzaRequest r);Task<bool> DeleteAsync(Guid id);Task<List<Scadenza>> GetProssimeAsync(int g);Task<List<Scadenza>> GetPerMeseAsync(int a,int m);Task<List<Scadenza>> GetPerResponsabileAsync(string rid);Task<List<Scadenza>> GetAlertAsync();}
public class ScadenzeService:IScadenzeService{private readonly ScadenzeRepository _r;public ScadenzeService(ScadenzeRepository r)=>_r=r;
public async Task<PagedResult<Scadenza>> GetAllAsync(int p,int ps,string? s,int? t,int? st){var items=await _r.GetAllAsync(p,ps,s,t,st);var total=await _r.CountAsync(s,t,st);return new PagedResult<Scadenza>{Items=items,TotalCount=total,Page=p,PageSize=ps};}
public Task<Scadenza?> GetByIdAsync(Guid id)=>_r.GetByIdAsync(id);
public async Task<Scadenza> CreateAsync(CreateScadenzaRequest r){var e=new Scadenza{Tipo=r.Tipo,Titolo=r.Titolo,Descrizione=r.Descrizione,DataScadenza=r.DataScadenza,GiorniPreavviso=r.GiorniPreavviso,Priorita=r.Priorita,Stato=r.Stato,EntitaRiferimento=r.EntitaRiferimento,EntitaId=r.EntitaId,ResponsabileId=r.ResponsabileId};return await _r.CreateAsync(e);}
public async Task<Scadenza?> UpdateAsync(Guid id,UpdateScadenzaRequest r){var e=await _r.GetByIdAsync(id);if(e==null)return null;e.Tipo=r.Tipo;e.Titolo=r.Titolo;e.Descrizione=r.Descrizione;e.DataScadenza=r.DataScadenza;e.GiorniPreavviso=r.GiorniPreavviso;e.Priorita=r.Priorita;e.Stato=r.Stato;e.EntitaRiferimento=r.EntitaRiferimento;e.EntitaId=r.EntitaId;e.ResponsabileId=r.ResponsabileId;e.UpdatedAt=DateTime.UtcNow;await _r.UpdateAsync(e);return e;}
public Task<bool> DeleteAsync(Guid id)=>_r.DeleteAsync(id);public Task<List<Scadenza>> GetProssimeAsync(int g)=>_r.GetProssimeAsync(g);public Task<List<Scadenza>> GetPerMeseAsync(int a,int m)=>_r.GetPerMeseAsync(a,m);public Task<List<Scadenza>> GetPerResponsabileAsync(string rid)=>_r.GetPerResponsabileAsync(rid);public Task<List<Scadenza>> GetAlertAsync()=>_r.GetAlertAsync();}
